load("//:helpers.bzl", "make_lib")

# Strips the RUNPATH and creates a local file "foo.so".
make_lib(
    name = "foo_imported_so_file",
    src = "//extension:foo_solib",
    out = "foo.so",
)

cc_library(
    name = "foo_so",
    srcs = ["foo.so"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "foo",
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "foo_so",
        "//libecho",
    ],
)

cc_library(
    name = "bar_lib",
    srcs = ["bar.cpp"],
)

cc_shared_library(
    name = "bar_solib",
    deps = ["bar_lib"],
)

make_lib(
    name = "bar_import",
    src = "bar_solib",
    out = "bar.so",
)

cc_library(
    name = "bar_so",
    srcs = ["bar.so"],
    visibility = ["//visibility:public"],
)
