---
name: bazel test

on:
  - push
  - workflow_dispatch

jobs:
  bazel-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        STATUS_CMD: ["status_ok.sh", "status_bad.sh"]
        USE_BAZEL_VERSION: ["7.x", "8.x", "9.x", "", "last_green"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: chrpath
          version: 1.0

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.12.1
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: USE_BAZEL_VERSION=${{ matrix.USE_BAZEL_VERSION }} bazelisk test ${{ matrix.STATUS_CMD }}
        run: |
          USE_BAZEL_VERSION=${{ matrix.USE_BAZEL_VERSION }} \
            bazelisk build --workspace_status_command=tools/${{ matrix.STATUS_CMD }} status_check && cat bazel-bin/status_check.txt
