---
name: bazel test

on:
  - push
  - workflow_dispatch

jobs:
  bazel-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: chrpath
          version: 1.0

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.12.1
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # # Store build cache per workflow.
          # disk-cache: false
          # Share repository cache between workflows.
          repository-cache: true

      - name: test_pass
        run: |
          bazelisk clean --async
          bazelisk test test_pass --config=bug

      - name: test_pass (non-hermetic)
        run: |
          bazelisk clean --async
          bazelisk test test_pass

      - name: test_fail
        run: |
          bazelisk clean --async
          ! bazelisk test test_fail --config=bug

      - name: test_fail (non-hermetic)
        run: |
          bazelisk clean --async
          ! bazelisk test test_fail
