on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1 2 * * 1" # weekly on Mondays

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        root:
          - .
          - mod_pytest
        version:
          - "6.x"
          - "7.x"
          - "latest"
          - "last_rc"
          - "last_green"
    steps:
    - uses: actions/checkout@v3

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Bazel Test
      run: |
        USE_BAZEL_VERSION=${{matrix.version}}
        export USE_BAZEL_VERSION
        bazel version
        cd "${{matrix.root}}"
        bazel test --announce_rc --test_output=errors ...
