on: [push, workflow_dispatch]

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - ""
          - "latest"
          - "last_rc"
    steps:
    - uses: actions/checkout@v3

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Bazel Test
      run: |
        USE_BAZEL_VERSION=${{matrix.version}} bazel test ...
