on: [push, workflow_dispatch]

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        root:
          - .
        version:
          - "7.x"
    steps:
    - uses: actions/checkout@v3

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Bazel Test
      run: |
        USE_BAZEL_VERSION=${{matrix.version}}
        export USE_BAZEL_VERSION
        bazel version
        cd "${{matrix.root}}"
        bazel test --test_output=errors ...
