on: [push, workflow_dispatch]

env:
  _BAZEL: bazel

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Bazel Test
      run: |
        ${_BAZEL} test pkg-opts/pkg1-use-features/...
        ${_BAZEL} test pkg-opts/pkg2-use-default/...
        ${_BAZEL} test pkg-opts/pkg3-use-macro/...
        ${_BAZEL} test py_test_env/...
