---
name: bazel test

on:
  - push
  - workflow_dispatch

jobs:
  bazel-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        USE_BAZEL_VERSION: [9.0.0, 8.5.1]
        FEATURES: ["", "--features=set_soname"]
    env:
      USE_BAZEL_VERSION: ${{ matrix.USE_BAZEL_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: binutils

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Share repository cache between workflows.
          repository-cache: true

      - name: test (Bazel ${{ matrix.USE_BAZEL_VERSION }} ${{ matrix.FEATURES }})
        run: |
          ./test.sh ${{ matrix.FEATURES }}
