---
name: bazel test

on:
  - push
  - workflow_dispatch

jobs:
  bazel-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: chrpath
          version: 1.0

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.12.1
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: bazelisk test
        run: |
          bazelisk test --test_output=all ...
